CREATE DATABASE BOOKSHOP
GO
USE BOOKSHOP
GO

CREATE TABLE NHAXUATBAN(
	ID INT PRIMARY KEY,
	TEN NVARCHAR(50) NOT NULL,
	SDT CHAR(13),
	DIACHI NVARCHAR(MAX),
	FAX CHAR(10),
	GIOITHIEU NVARCHAR(MAX),
	ISDELETE BIT DEFAULT 0
)

CREATE TABLE CHUDE(
	ID INT PRIMARY KEY,
	TEN NVARCHAR(50) NOT NULL,
	ISDELETE BIT DEFAULT 0
)

CREATE TABLE SACH(
	ID INT PRIMARY KEY,
	TEN NVARCHAR(50) NOT NULL,
	GIABAN INT,
	GIANHAP INT,
	MOTA NVARCHAR(MAX),
	ID_CHUDE INT REFERENCES CHUDE(ID),
	ID_NXB INT REFERENCES NHAXUATBAN(ID),
	BIA VARCHAR(MAX),
	SOLUONG INT,
	KHO CHAR(50),
	SOTRANG INT,
	ISDELETE BIT DEFAULT 0
)

CREATE TABLE PHIEUNHAP(
	ID INT PRIMARY KEY,
	ID_NXB INT REFERENCES NHAXUATBAN(ID),
	NGAYNHAP DATETIME,
	SOLUONG INT,
	ISDELETE BIT DEFAULT 0
)

CREATE TABLE CHITIETPHIEUNHAP(
	ID_PN INT REFERENCES PHIEUNHAP(ID),
	ID_SACH INT REFERENCES SACH(ID),
	SOLUONG INT,
	PRIMARY KEY(ID_PN,ID_SACH),
	ISDELETE BIT DEFAULT 0
)

CREATE TABLE TACGIA(
	ID INT PRIMARY KEY,
	TEN NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(50),
	SDT CHAR(13),
	ISDELETE BIT DEFAULT 0
)

CREATE TABLE VIETSACH(
	ID_SACH INT REFERENCES SACH(ID),
	ID_TACGIA INT REFERENCES TACGIA(ID),
	NGAYVIET DATETIME,
	VAITRO NVARCHAR(20),
	PRIMARY KEY (ID_SACH,ID_TACGIA),
	ISDELETE BIT DEFAULT 0
)

CREATE TABLE DATHANG(
	ID INT PRIMARY KEY,
	SOLUONG INT,
	TENKH NVARCHAR(50) NOT NULL,
	SDTKH CHAR(13),
	DIACHIKH NVARCHAR(50),
	NGAYDAT DATETIME,
	ISDELETE BIT DEFAULT 0
)

CREATE TABLE CHITIETDATHANG
(
	ID_DH INT REFERENCES DATHANG(ID),
	TENSACH NVARCHAR(50) NOT NULL,
	SOLUONG INT,
	PRIMARY KEY(ID_DH,TENSACH),
	ISDELETE BIT DEFAULT 0
)

CREATE TABLE PHANQUYEN(
	ID INT PRIMARY KEY,
	TEN NVARCHAR(50) NOT NULL,
	ISDELETE BIT DEFAULT 0
)

CREATE TABLE NHANVIEN(
	ID INT PRIMARY KEY,
	TEN NVARCHAR(50) NOT NULL,
	NGAYSINH DATETIME,
	SDT CHAR(13),
	TENDANGNHAP NVARCHAR(20),
	MATKHAU CHAR(10),
	ID_QUYEN INT REFERENCES PHANQUYEN(ID),
	ISDELETE BIT DEFAULT 0
)

CREATE TABLE KHUYENMAI(
	ID INT PRIMARY KEY,
	TENKM NVARCHAR(50),
	NGAYBATDAU DATETIME,
	NGAYKETTHUC DATETIME,
	ISDELETE BIT DEFAULT 0
)

CREATE TABLE CHITIETKM(
	ID_KM INT REFERENCES KHUYENMAI(ID),
	ID_SACH INT REFERENCES SACH(ID),
	PTKM INT,
	PRIMARY KEY(ID_KM,ID_SACH),
	ISDELETE BIT DEFAULT 0
)

CREATE TABLE HOADON(
	ID INT PRIMARY KEY,
	ID_NV INT REFERENCES NHANVIEN(ID),
	THANHTIEN INT,
	NGAY DATETIME,
	SOLUONG INT,
	ISDELETE BIT DEFAULT 0
)

CREATE TABLE CHITIETHOADON(
	ID_HD INT REFERENCES HOADON(ID),
	ID_SACH INT REFERENCES SACH(ID),
	SOLUONG INT,
	GIA INT,
	PTKM INT,
	PRIMARY KEY(ID_HD,ID_SACH),
	ISDELETE BIT DEFAULT 0
)